# To load a csv File

In [1]:
import pandas as pd

In [8]:
df = pd.read_csv('monthly_sales.csv')
df.head() # to print first 5 records
df.tail() # to print last 5 records

      month region    product  units  price_per_unit
45  2024-11   East  Product_C     84           55.35
46  2024-11   East  Product_C     57           95.77
47  2024-11   East  Product_D    197           66.29
48  2024-12   West  Product_A    122           67.20
49  2024-12   East  Product_D     85           80.20

# To load a json File

In [9]:
df = pd.read_json('sample1.json')
df

    id        name    class  marks
0    1   Student 1  Class A     81
1    2   Student 2  Class B     72
2    3   Student 3  Class C     65
3    4   Student 4  Class A     90
4    5   Student 5  Class B     58
5    6   Student 6  Class C     76
6    7   Student 7  Class A     84
7    8   Student 8  Class B     69
8    9   Student 9  Class C     73
9   10  Student 10  Class A     62
10  11  Student 11  Class B     88
11  12  Student 12  Class C     91
12  13  Student 13  Class A     55
13  14  Student 14  Class B     79
14  15  Student 15  Class C     67
15  16  Student 16  Class A     82
16  17  Student 17  Class B     74
17  18  Student 18  Class C     63
18  19  Student 19  Class A     95
19  20  Student 20  Class B     61
20  21  Student 21  Class C     77
21  22  Student 22  Class A     89
22  23  Student 23  Class B     70
23  24  Student 24  Class C     64
24  25  Student 25  Class A     83
25  26  Student 26  Class B     56
26  27  Student 27  Class C     92
27  28  Student 28  Class A     68
28  29  Student 29  Class B     71
29  30  Student 30  Class C     60
30  31  Student 31  Class A     86
31  32  Student 32  Class B     78
32  33  Student 33  Class C     66
33  34  Student 34  Class A     93
34  35  Student 35  Class B     59
35  36  Student 36  Class C     80
36  37  Student 37  Class A     72
37  38  Student 38  Class B     65
38  39  Student 39  Class C     90
39  40  Student 40  Class A     57
40  41  Student 41  Class B     75
41  42  Student 42  Class C     88
42  43  Student 43  Class A     69
43  44  Student 44  Class B     81
44  45  Student 45  Class C     62
45  46  Student 46  Class A     85
46  47  Student 47  Class B     73
47  48  Student 48  Class C     94
48  49  Student 49  Class A     78
49  50  Student 50  Class B     64

# Data Selection

In [20]:
df = pd.read_csv('monthly_sales.csv')
df 
# df[["month","region","units"]]#to select specific column

      month region    product  units  price_per_unit
0   2024-01   West  Product_A    126           44.17
1   2024-01   East  Product_B    126           90.79
2   2024-01   West  Product_B    166           84.29
3   2024-01   West  Product_A     88           84.74
4   2024-01  South  Product_B     67           61.98
5   2024-02   West  Product_B    104           62.82
6   2024-02   West  Product_B     55           56.84
7   2024-02   West  Product_C    198           40.66
8   2024-02   West  Product_C    110           85.44
9   2024-03  South  Product_C     64           59.41
10  2024-03   East  Product_D     54           42.25
11  2024-03  South  Product_A     45           99.28
12  2024-03  North  Product_D     68           99.32
13  2024-04   East  Product_B     57           71.80
14  2024-04   East  Product_A     37           75.81
15  2024-04  North  Product_D     29           50.37
16  2024-04  North  Product_B    173           92.05
17  2024-04  North  Product_B     12           71.00
18  2024-05   East  Product_C     99           79.44
19  2024-05  South  Product_A     81           60.56
20  2024-05   East  Product_C     58           84.75
21  2024-05  South  Product_D    178           72.39
22  2024-06   West  Product_A    188           89.28
23  2024-06  North  Product_B     24           49.53
24  2024-06   West  Product_C     56           81.39
25  2024-06   East  Product_A    168           63.76
26  2024-07  North  Product_C    193           68.16
27  2024-07   East  Product_B    169           84.48
28  2024-07  South  Product_B    186           82.09
29  2024-07  North  Product_A    189           66.05
30  2024-07  South  Product_D     27           81.69
31  2024-08  South  Product_A    110           65.39
32  2024-08  South  Product_C     55           64.98
33  2024-08   East  Product_D    177           58.04
34  2024-08  South  Product_B     41           66.61
35  2024-09  South  Product_D     54           69.91
36  2024-09   West  Product_B    125           68.59
37  2024-09  South  Product_B    183           59.40
38  2024-09   West  Product_B    200           41.55
39  2024-09   East  Product_A     25           54.48
40  2024-10  South  Product_C    134           80.87
41  2024-10  North  Product_B     51           93.45
42  2024-10  North  Product_B     20           46.26
43  2024-10  South  Product_A     58           98.62
44  2024-11   West  Product_B     85           78.08
45  2024-11   East  Product_C     84           55.35
46  2024-11   East  Product_C     57           95.77
47  2024-11   East  Product_D    197           66.29
48  2024-12   West  Product_A    122           67.20
49  2024-12   East  Product_D     85           80.20

# Row selection

In [24]:
df = pd.read_csv("monthly_sales.csv",index_col="month")
print(df.loc["2024-02"])

        region    product  units  price_per_unit
month
2024-02   West  Product_B    104           62.82
2024-02   West  Product_B     55           56.84
2024-02   West  Product_C    198           40.66
2024-02   West  Product_C    110           85.44

In [ ]:
print(df.loc["2024-02":"2024-03	", ["region","units"]])
#from 2024-03 to 2024-03 region and uinits will print

        region  units
month
2024-02   West    104
2024-02   West     55
2024-02   West    198
2024-02   West    110
2024-03  South     64
2024-03   East     54
2024-03  South     45
2024-03  North     68

In [32]:
print(df.iloc[0:5,2:3])

         units
month
2024-01    126
2024-01    126
2024-01    166
2024-01     88
2024-01     67

# FIltering in pandas

In [33]:
df = pd.read_json('sample1.json')
df

    id        name    class  marks
0    1   Student 1  Class A     81
1    2   Student 2  Class B     72
2    3   Student 3  Class C     65
3    4   Student 4  Class A     90
4    5   Student 5  Class B     58
5    6   Student 6  Class C     76
6    7   Student 7  Class A     84
7    8   Student 8  Class B     69
8    9   Student 9  Class C     73
9   10  Student 10  Class A     62
10  11  Student 11  Class B     88
11  12  Student 12  Class C     91
12  13  Student 13  Class A     55
13  14  Student 14  Class B     79
14  15  Student 15  Class C     67
15  16  Student 16  Class A     82
16  17  Student 17  Class B     74
17  18  Student 18  Class C     63
18  19  Student 19  Class A     95
19  20  Student 20  Class B     61
20  21  Student 21  Class C     77
21  22  Student 22  Class A     89
22  23  Student 23  Class B     70
23  24  Student 24  Class C     64
24  25  Student 25  Class A     83
25  26  Student 26  Class B     56
26  27  Student 27  Class C     92
27  28  Student 28  Class A     68
28  29  Student 29  Class B     71
29  30  Student 30  Class C     60
30  31  Student 31  Class A     86
31  32  Student 32  Class B     78
32  33  Student 33  Class C     66
33  34  Student 34  Class A     93
34  35  Student 35  Class B     59
35  36  Student 36  Class C     80
36  37  Student 37  Class A     72
37  38  Student 38  Class B     65
38  39  Student 39  Class C     90
39  40  Student 40  Class A     57
40  41  Student 41  Class B     75
41  42  Student 42  Class C     88
42  43  Student 43  Class A     69
43  44  Student 44  Class B     81
44  45  Student 45  Class C     62
45  46  Student 46  Class A     85
46  47  Student 47  Class B     73
47  48  Student 48  Class C     94
48  49  Student 49  Class A     78
49  50  Student 50  Class B     64

In [ ]:
# filtered = df[df['class']!="Class A"] #for single condition
filtered = df[(df['class']=='Class A')|(df['marks']>90)] #for multiple condition we can use &,|,!
filtered

    id        name    class  marks
0    1   Student 1  Class A     81
3    4   Student 4  Class A     90
6    7   Student 7  Class A     84
9   10  Student 10  Class A     62
11  12  Student 12  Class C     91
12  13  Student 13  Class A     55
15  16  Student 16  Class A     82
18  19  Student 19  Class A     95
21  22  Student 22  Class A     89
24  25  Student 25  Class A     83
26  27  Student 27  Class C     92
27  28  Student 28  Class A     68
30  31  Student 31  Class A     86
33  34  Student 34  Class A     93
36  37  Student 37  Class A     72
39  40  Student 40  Class A     57
42  43  Student 43  Class A     69
45  46  Student 46  Class A     85
47  48  Student 48  Class C     94
48  49  Student 49  Class A     78