# To load a csv File

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('monthly_sales.csv')
df.head() # to print first 5 records
df.tail() # to print last 5 records

      month region    product  units  price_per_unit
45  2024-11   East  Product_C     84           55.35
46  2024-11   East  Product_C     57           95.77
47  2024-11   East  Product_D    197           66.29
48  2024-12   West  Product_A    122           67.20
49  2024-12   East  Product_D     85           80.20

# To load a json File

In [4]:
df = pd.read_json('sample1.json')
df

    id        name    class  marks
0    1   Student 1  Class A     81
1    1   Student 1  Class A     81
2    2   Student 2  Class B     72
3    2   Student 2  Class B     72
4    3   Student 3  Class C     65
5    3   Student 3  Class C     65
6    4   Student 4  Class A     90
7    5   Student 5  Class B     58
8    6   Student 6  Class C     76
9    7   Student 7  Class A     84
10   8   Student 8  Class B     69
11   9   Student 9  Class C     73
12  10  Student 10  Class A     62
13  11  Student 11  Class B     88
14  12  Student 12  Class C     91
15  13  Student 13  Class A     55
16  14  Student 14  Class B     79
17  15  Student 15  Class C     67
18  16  Student 16  Class A     82
19  17  Student 17  Class B     74
20  18  Student 18  Class C     63
21  19  Student 19  Class A     95
22  20  Student 20  Class B     61
23  21  Student 21  Class C     77
24  22  Student 22  Class A     89
25  23  Student 23  Class B     70
26  24  Student 24  Class C     64
27  25  Student 25  Class A     83
28  26  Student 26  Class B     56
29  27  Student 27  Class C     92
30  28  Student 28  Class A     68
31  29  Student 29  Class B     71
32  30  Student 30  Class C     60
33  31  Student 31  Class A     86
34  32  Student 32  Class B     78
35  33  Student 33  Class C     66
36  34  Student 34  Class A     93
37  35  Student 35  Class B     59
38  36  Student 36  Class C     80
39  37  Student 37  Class A     72
40  38  Student 38  Class B     65
41  39  Student 39  Class C     90
42  40  Student 40  Class A     57
43  41  Student 41  Class B     75
44  42  Student 42  Class C     88
45  43  Student 43  Class A     69
46  44  Student 44  Class B     81
47  45  Student 45  Class C     62
48  46  Student 46  Class A     85
49  47  Student 47  Class B     73
50  48  Student 48  Class C     94
51  49  Student 49  Class A     78
52  50  Student 50  Class B     64

# Data Selection

In [5]:
df = pd.read_csv('monthly_sales.csv')
df 
df[["month","region","units"]]#to select specific column

      month region  units
0   2024-01   West    126
1   2024-01   East    126
2   2024-01   West    166
3   2024-01   West     88
4   2024-01  South     67
5   2024-02   West    104
6   2024-02   West     55
7   2024-02   West    198
8   2024-02   West    110
9   2024-03  South     64
10  2024-03   East     54
11  2024-03  South     45
12  2024-03  North     68
13  2024-04   East     57
14  2024-04   East     37
15  2024-04  North     29
16  2024-04  North    173
17  2024-04  North     12
18  2024-05   East     99
19  2024-05  South     81
20  2024-05   East     58
21  2024-05  South    178
22  2024-06   West    188
23  2024-06  North     24
24  2024-06   West     56
25  2024-06   East    168
26  2024-07  North    193
27  2024-07   East    169
28  2024-07  South    186
29  2024-07  North    189
30  2024-07  South     27
31  2024-08  South    110
32  2024-08  South     55
33  2024-08   East    177
34  2024-08  South     41
35  2024-09  South     54
36  2024-09   West    125
37  2024-09  South    183
38  2024-09   West    200
39  2024-09   East     25
40  2024-10  South    134
41  2024-10  North     51
42  2024-10  North     20
43  2024-10  South     58
44  2024-11   West     85
45  2024-11   East     84
46  2024-11   East     57
47  2024-11   East    197
48  2024-12   West    122
49  2024-12   East     85

# Row selection

In [6]:
df = pd.read_csv("monthly_sales.csv",index_col="month")
print(df.loc["2024-02"])

        region    product  units  price_per_unit
month
2024-02   West  Product_B    104           62.82
2024-02   West  Product_B     55           56.84
2024-02   West  Product_C    198           40.66
2024-02   West  Product_C    110           85.44

In [7]:
print(df.loc["2024-02":"2024-03	", ["region","units"]])
#from 2024-03 to 2024-03 region and uinits will print

        region  units
month
2024-02   West    104
2024-02   West     55
2024-02   West    198
2024-02   West    110
2024-03  South     64
2024-03   East     54
2024-03  South     45
2024-03  North     68

In [8]:
print(df.iloc[0:5,2:3])

         units
month
2024-01    126
2024-01    126
2024-01    166
2024-01     88
2024-01     67

# FIltering in pandas

In [9]:
df = pd.read_json('sample1.json')
df

    id        name    class  marks
0    1   Student 1  Class A     81
1    1   Student 1  Class A     81
2    2   Student 2  Class B     72
3    2   Student 2  Class B     72
4    3   Student 3  Class C     65
5    3   Student 3  Class C     65
6    4   Student 4  Class A     90
7    5   Student 5  Class B     58
8    6   Student 6  Class C     76
9    7   Student 7  Class A     84
10   8   Student 8  Class B     69
11   9   Student 9  Class C     73
12  10  Student 10  Class A     62
13  11  Student 11  Class B     88
14  12  Student 12  Class C     91
15  13  Student 13  Class A     55
16  14  Student 14  Class B     79
17  15  Student 15  Class C     67
18  16  Student 16  Class A     82
19  17  Student 17  Class B     74
20  18  Student 18  Class C     63
21  19  Student 19  Class A     95
22  20  Student 20  Class B     61
23  21  Student 21  Class C     77
24  22  Student 22  Class A     89
25  23  Student 23  Class B     70
26  24  Student 24  Class C     64
27  25  Student 25  Class A     83
28  26  Student 26  Class B     56
29  27  Student 27  Class C     92
30  28  Student 28  Class A     68
31  29  Student 29  Class B     71
32  30  Student 30  Class C     60
33  31  Student 31  Class A     86
34  32  Student 32  Class B     78
35  33  Student 33  Class C     66
36  34  Student 34  Class A     93
37  35  Student 35  Class B     59
38  36  Student 36  Class C     80
39  37  Student 37  Class A     72
40  38  Student 38  Class B     65
41  39  Student 39  Class C     90
42  40  Student 40  Class A     57
43  41  Student 41  Class B     75
44  42  Student 42  Class C     88
45  43  Student 43  Class A     69
46  44  Student 44  Class B     81
47  45  Student 45  Class C     62
48  46  Student 46  Class A     85
49  47  Student 47  Class B     73
50  48  Student 48  Class C     94
51  49  Student 49  Class A     78
52  50  Student 50  Class B     64

In [11]:
# filtered = df[df['class']!="Class A"] #for single condition
filtered = df[(df['class']=='Class A')&(df['marks']>90)] #for multiple condition we can use &,|,!
filtered

    id        name    class  marks
21  19  Student 19  Class A     95
36  34  Student 34  Class A     93

# Aggregate in Pandas

In [12]:
df = pd.read_json('sample1.json')
df

    id        name    class  marks
0    1   Student 1  Class A     81
1    1   Student 1  Class A     81
2    2   Student 2  Class B     72
3    2   Student 2  Class B     72
4    3   Student 3  Class C     65
5    3   Student 3  Class C     65
6    4   Student 4  Class A     90
7    5   Student 5  Class B     58
8    6   Student 6  Class C     76
9    7   Student 7  Class A     84
10   8   Student 8  Class B     69
11   9   Student 9  Class C     73
12  10  Student 10  Class A     62
13  11  Student 11  Class B     88
14  12  Student 12  Class C     91
15  13  Student 13  Class A     55
16  14  Student 14  Class B     79
17  15  Student 15  Class C     67
18  16  Student 16  Class A     82
19  17  Student 17  Class B     74
20  18  Student 18  Class C     63
21  19  Student 19  Class A     95
22  20  Student 20  Class B     61
23  21  Student 21  Class C     77
24  22  Student 22  Class A     89
25  23  Student 23  Class B     70
26  24  Student 24  Class C     64
27  25  Student 25  Class A     83
28  26  Student 26  Class B     56
29  27  Student 27  Class C     92
30  28  Student 28  Class A     68
31  29  Student 29  Class B     71
32  30  Student 30  Class C     60
33  31  Student 31  Class A     86
34  32  Student 32  Class B     78
35  33  Student 33  Class C     66
36  34  Student 34  Class A     93
37  35  Student 35  Class B     59
38  36  Student 36  Class C     80
39  37  Student 37  Class A     72
40  38  Student 38  Class B     65
41  39  Student 39  Class C     90
42  40  Student 40  Class A     57
43  41  Student 41  Class B     75
44  42  Student 42  Class C     88
45  43  Student 43  Class A     69
46  44  Student 44  Class B     81
47  45  Student 45  Class C     62
48  46  Student 46  Class A     85
49  47  Student 47  Class B     73
50  48  Student 48  Class C     94
51  49  Student 49  Class A     78
52  50  Student 50  Class B     64

In [13]:
print(df.mean(numeric_only=True)) #it only take average of only numeric values
print(df.max(numeric_only=True))
print(df["marks"].min()) #we are specifying a particular column for min
print(df["marks"].sum())

id       24.169811
marks    74.490566
dtype: float64
id       50
marks    95
dtype: int64
55
3948

# Group by

In [14]:
group = df.groupby("marks")
group
# print(group.mean(numeric_only=True))
print(group["marks"].sum())

marks
55     55
56     56
57     57
58     58
59     59
60     60
61     61
62    124
63     63
64    128
65    195
66     66
67     67
68     68
69    138
70     70
71     71
72    216
73    146
74     74
75     75
76     76
77     77
78    156
79     79
80     80
81    243
82     82
83     83
84     84
85     85
86     86
88    176
89     89
90    180
91     91
92     92
93     93
94     94
95     95
Name: marks, dtype: int64