# Data Cleaning using pandas

In [1]:
import pandas as pd

In [2]:
df = pd.read_json('sample1.json')
df.head()

   id       name    class  marks
0   1  Student 1  Class A     81
1   1  Student 1  Class A     81
2   2  Student 2  Class B     72
3   2  Student 2  Class B     72
4   3  Student 3  Class C     65

# dropping a cloumn

In [3]:
df = df.drop(columns=["id"])
df.head()

        name    class  marks
0  Student 1  Class A     81
1  Student 1  Class A     81
2  Student 2  Class B     72
3  Student 2  Class B     72
4  Student 3  Class C     65

# To clean NaN in data

In [4]:
df = df.dropna(subset=["marks"])
df

          name    class  marks
0    Student 1  Class A     81
1    Student 1  Class A     81
2    Student 2  Class B     72
3    Student 2  Class B     72
4    Student 3  Class C     65
5    Student 3  Class C     65
6    Student 4  Class A     90
7    Student 5  Class B     58
8    Student 6  Class C     76
9    Student 7  Class A     84
10   Student 8  Class B     69
11   Student 9  Class C     73
12  Student 10  Class A     62
13  Student 11  Class B     88
14  Student 12  Class C     91
15  Student 13  Class A     55
16  Student 14  Class B     79
17  Student 15  Class C     67
18  Student 16  Class A     82
19  Student 17  Class B     74
20  Student 18  Class C     63
21  Student 19  Class A     95
22  Student 20  Class B     61
23  Student 21  Class C     77
24  Student 22  Class A     89
25  Student 23  Class B     70
26  Student 24  Class C     64
27  Student 25  Class A     83
28  Student 26  Class B     56
29  Student 27  Class C     92
30  Student 28  Class A     68
31  Student 29  Class B     71
32  Student 30  Class C     60
33  Student 31  Class A     86
34  Student 32  Class B     78
35  Student 33  Class C     66
36  Student 34  Class A     93
37  Student 35  Class B     59
38  Student 36  Class C     80
39  Student 37  Class A     72
40  Student 38  Class B     65
41  Student 39  Class C     90
42  Student 40  Class A     57
43  Student 41  Class B     75
44  Student 42  Class C     88
45  Student 43  Class A     69
46  Student 44  Class B     81
47  Student 45  Class C     62
48  Student 46  Class A     85
49  Student 47  Class B     73
50  Student 48  Class C     94
51  Student 49  Class A     78
52  Student 50  Class B     64

# if we have an NaN in an column instead of NaN we can define what value need to present in the NaN position

In [5]:
df = df.fillna({
    "marks":99
})
df

          name    class  marks
0    Student 1  Class A     81
1    Student 1  Class A     81
2    Student 2  Class B     72
3    Student 2  Class B     72
4    Student 3  Class C     65
5    Student 3  Class C     65
6    Student 4  Class A     90
7    Student 5  Class B     58
8    Student 6  Class C     76
9    Student 7  Class A     84
10   Student 8  Class B     69
11   Student 9  Class C     73
12  Student 10  Class A     62
13  Student 11  Class B     88
14  Student 12  Class C     91
15  Student 13  Class A     55
16  Student 14  Class B     79
17  Student 15  Class C     67
18  Student 16  Class A     82
19  Student 17  Class B     74
20  Student 18  Class C     63
21  Student 19  Class A     95
22  Student 20  Class B     61
23  Student 21  Class C     77
24  Student 22  Class A     89
25  Student 23  Class B     70
26  Student 24  Class C     64
27  Student 25  Class A     83
28  Student 26  Class B     56
29  Student 27  Class C     92
30  Student 28  Class A     68
31  Student 29  Class B     71
32  Student 30  Class C     60
33  Student 31  Class A     86
34  Student 32  Class B     78
35  Student 33  Class C     66
36  Student 34  Class A     93
37  Student 35  Class B     59
38  Student 36  Class C     80
39  Student 37  Class A     72
40  Student 38  Class B     65
41  Student 39  Class C     90
42  Student 40  Class A     57
43  Student 41  Class B     75
44  Student 42  Class C     88
45  Student 43  Class A     69
46  Student 44  Class B     81
47  Student 45  Class C     62
48  Student 46  Class A     85
49  Student 47  Class B     73
50  Student 48  Class C     94
51  Student 49  Class A     78
52  Student 50  Class B     64

# To replace a value

In [22]:
df['class'] = df['class'].replace({
    "Class A": "IT",
    "Class B": "CSE",
    "Class C": "EEE"
})
df

    id        name class  marks
0    1   Student 1    IT   99.0
1    2   Student 2   CSE   99.0
2    3   Student 3   EEE   65.0
3    4   Student 4    IT   90.0
4    5   Student 5   CSE   58.0
5    6   Student 6   EEE   76.0
6    7   Student 7    IT   84.0
7    8   Student 8   CSE   69.0
8    9   Student 9   EEE   73.0
9   10  Student 10    IT   62.0
10  11  Student 11   CSE   88.0
11  12  Student 12   EEE   91.0
12  13  Student 13    IT   55.0
13  14  Student 14   CSE   79.0
14  15  Student 15   EEE   67.0
15  16  Student 16    IT   82.0
16  17  Student 17   CSE   74.0
17  18  Student 18   EEE   63.0
18  19  Student 19    IT   95.0
19  20  Student 20   CSE   61.0
20  21  Student 21   EEE   77.0
21  22  Student 22    IT   89.0
22  23  Student 23   CSE   70.0
23  24  Student 24   EEE   64.0
24  25  Student 25    IT   83.0
25  26  Student 26   CSE   56.0
26  27  Student 27   EEE   92.0
27  28  Student 28    IT   68.0
28  29  Student 29   CSE   71.0
29  30  Student 30   EEE   60.0
30  31  Student 31    IT   86.0
31  32  Student 32   CSE   78.0
32  33  Student 33   EEE   66.0
33  34  Student 34    IT   93.0
34  35  Student 35   CSE   59.0
35  36  Student 36   EEE   80.0
36  37  Student 37    IT   72.0
37  38  Student 38   CSE   65.0
38  39  Student 39   EEE   90.0
39  40  Student 40    IT   57.0
40  41  Student 41   CSE   75.0
41  42  Student 42   EEE   88.0
42  43  Student 43    IT   69.0
43  44  Student 44   CSE   81.0
44  45  Student 45   EEE   62.0
45  46  Student 46    IT   85.0
46  47  Student 47   CSE   73.0
47  48  Student 48   EEE   94.0
48  49  Student 49    IT   78.0
49  50  Student 50   CSE   64.0

# To remove duplicates

In [6]:
df = df.drop_duplicates()
df

          name    class  marks
0    Student 1  Class A     81
2    Student 2  Class B     72
4    Student 3  Class C     65
6    Student 4  Class A     90
7    Student 5  Class B     58
8    Student 6  Class C     76
9    Student 7  Class A     84
10   Student 8  Class B     69
11   Student 9  Class C     73
12  Student 10  Class A     62
13  Student 11  Class B     88
14  Student 12  Class C     91
15  Student 13  Class A     55
16  Student 14  Class B     79
17  Student 15  Class C     67
18  Student 16  Class A     82
19  Student 17  Class B     74
20  Student 18  Class C     63
21  Student 19  Class A     95
22  Student 20  Class B     61
23  Student 21  Class C     77
24  Student 22  Class A     89
25  Student 23  Class B     70
26  Student 24  Class C     64
27  Student 25  Class A     83
28  Student 26  Class B     56
29  Student 27  Class C     92
30  Student 28  Class A     68
31  Student 29  Class B     71
32  Student 30  Class C     60
33  Student 31  Class A     86
34  Student 32  Class B     78
35  Student 33  Class C     66
36  Student 34  Class A     93
37  Student 35  Class B     59
38  Student 36  Class C     80
39  Student 37  Class A     72
40  Student 38  Class B     65
41  Student 39  Class C     90
42  Student 40  Class A     57
43  Student 41  Class B     75
44  Student 42  Class C     88
45  Student 43  Class A     69
46  Student 44  Class B     81
47  Student 45  Class C     62
48  Student 46  Class A     85
49  Student 47  Class B     73
50  Student 48  Class C     94
51  Student 49  Class A     78
52  Student 50  Class B     64