# Dataframe in pandas
In pandas, a DataFrame is:

A 2‑dimensional labeled table (rows × columns).
Each column is a Series (so a DataFrame is like a collection of Series sharing the same row index).
Columns can have different data types (int, float, string, datetime, etc.).
Very similar to:
A table in a database,
An Excel sheet, or
A CSV file loaded into memory.

In [3]:
import pandas as pd

In [4]:
student = {
    "Name":["Messi","Neymar","Lamine","Gavi","Pedri"],
    "Age":[38,32,18,22,24],
    "CGPA":[9.9,8.7,8.0,9.1,9.2]
}
df = pd.DataFrame(student)
df

     Name  Age  CGPA
0   Messi   38   9.9
1  Neymar   32   8.7
2  Lamine   18   8.0
3    Gavi   22   9.1
4   Pedri   24   9.2

Giving index of our own

In [5]:
df = pd.DataFrame(student,index=["Std1","Std2","Std3","Std4","Std5"])
df

        Name  Age  CGPA
Std1   Messi   38   9.9
Std2  Neymar   32   8.7
Std3  Lamine   18   8.0
Std4    Gavi   22   9.1
Std5   Pedri   24   9.2

Accessing element using index

In [6]:
print(df.loc["Std1"])
print(df.iloc[1])

Name    Messi
Age        38
CGPA      9.9
Name: Std1, dtype: object
Name    Neymar
Age         32
CGPA       8.7
Name: Std2, dtype: object

To add a new column

In [7]:
df["Medium"] = ["English","English","Tamil","Tamil","Tamil"]

In [8]:
df

        Name  Age  CGPA   Medium
Std1   Messi   38   9.9  English
Std2  Neymar   32   8.7  English
Std3  Lamine   18   8.0    Tamil
Std4    Gavi   22   9.1    Tamil
Std5   Pedri   24   9.2    Tamil

To add a new row

In [9]:
std4 = pd.DataFrame({"Name":"RashFord","Age":28,"CGPA":8.8,"Medium":"CBSE"},index=["Std 6"])

In [10]:
df = pd.concat([df,std4])
df

           Name  Age  CGPA   Medium
Std1      Messi   38   9.9  English
Std2     Neymar   32   8.7  English
Std3     Lamine   18   8.0    Tamil
Std4       Gavi   22   9.1    Tamil
Std5      Pedri   24   9.2    Tamil
Std 6  RashFord   28   8.8     CBSE

TO add Multiple rows

In [11]:
student = pd.DataFrame([
    {"Name":"Dani Olama", "Age":28,"CGPA":8.7,"Medium":"English"},
    {"Name":"Curbasi","Age":22,"CGPA":8.9,"Medium":"English"}
],index=["Std7","Std8"])

In [12]:
df = pd.concat([df,student])
df

             Name  Age  CGPA   Medium
Std1        Messi   38   9.9  English
Std2       Neymar   32   8.7  English
Std3       Lamine   18   8.0    Tamil
Std4         Gavi   22   9.1    Tamil
Std5        Pedri   24   9.2    Tamil
Std 6    RashFord   28   8.8     CBSE
Std7   Dani Olama   28   8.7  English
Std8      Curbasi   22   8.9  English

In [15]:
# Remove duplicate rows based on all columns, keep first occurrence
df = df.drop_duplicates(keep="first")
# Filter out rows matching that specific record
df = df[~((df["Name"] == "Dani Olama") &
          (df["Age"] == 28) &
          (df["CGPA"] == 8.8))]
df

Empty DataFrame
Columns: [Name, Age, CGPA, Medium]
Index: []

#  Small End-to-End Analysis

In [22]:
import pandas as pd

# 1) Load data (assume CSV of monthly sales)
df = pd.read_csv("monthly_sales.csv")
# Columns: month, region, product, units, price_per_unit

# 2) Create revenue column
df["revenue"] = df["units"] * df["price_per_unit"]

# 3) Basic checks
print(df.head())
print(df.describe())

# 4) Total revenue by region
rev_by_region = df.groupby("region")["revenue"].sum()

# 5) Top 5 months by revenue
top_months = df.sort_values(by="revenue", ascending=False).head(5)

print("Revenue by region:")
print(rev_by_region)

print("Top 5 month-level rows by revenue:")
print(top_months)

     month region    product  units  price_per_unit   revenue
0  2024-01   West  Product_A    126           44.17   5565.42
1  2024-01   East  Product_B    126           90.79  11439.54
2  2024-01   West  Product_B    166           84.29  13992.14
3  2024-01   West  Product_A     88           84.74   7457.12
4  2024-01  South  Product_B     67           61.98   4152.66
            units  price_per_unit       revenue
count   50.000000       50.000000     50.000000
mean   101.160000       70.952600   7141.766400
std     59.473321       16.118777   4345.692589
min     12.000000       40.660000    852.000000
25%     55.000000       59.697500   3874.830000
50%     85.000000       69.250000   6585.040000
75%    167.500000       83.740000  10602.030000
max    200.000000       99.320000  16784.640000
Revenue by region:
region
East     100006.97
North     57509.34
South     92387.34
West     107184.67
Name: revenue, dtype: float64
Top 5 month-level rows by revenue:
      month region    product  units  price_per_unit   revenue
22  2024-06   West  Product_A    188           89.28  16784.64
16  2024-04  North  Product_B    173           92.05  15924.65
28  2024-07  South  Product_B    186           82.09  15268.74
27  2024-07   East  Product_B    169           84.48  14277.12
2   2024-01   West  Product_B    166           84.29  13992.14