# Data cleaning = the process of fixing/Removing:
iincomplete, incorrect or irrelevant data.
~75% of work done with pandas is data cleaning.

In [16]:
import pandas as pd

In [17]:
df = pd.read_csv('Dataset_Sample.csv')
df.head()

   No        Name  Type1   Type2  Height  Weight  Legendary
0   1   Bulbasaur  Grass  Poison     0.7     6.9          0
1   2     Ivysaur  Grass  Poison     1.0    13.0          0
2   3    Venusaur  Grass  Poison     2.0   100.0          0
3   4  Charmander   Fire     NaN     0.6     8.5          0
4   5  Charmeleon   Fire     NaN     1.1    19.0          0

# Drop irrelevant columns

In [ ]:
df = df.drop(columns=['Legendary','No']) #removing the column legendary and no form the dataset
df

           Name    Type1   Type2  Height  Weight
0     Bulbasaur    Grass  Poison     0.7     6.9
1       Ivysaur    Grass  Poison     1.0    13.0
2      Venusaur    Grass  Poison     2.0   100.0
3    Charmander     Fire     NaN     0.6     8.5
4    Charmeleon     Fire     NaN     1.1    19.0
..          ...      ...     ...     ...     ...
145     Moltres     Fire  Flying     2.0    60.0
146     Dratini   Dragon     NaN     1.8     3.3
147   Dragonair   Dragon     NaN     4.0    16.5
148   Dragonite   Dragon  Flying     2.2   210.0
149      Mewtwo  Psychic     NaN     2.0   122.0

[150 rows x 5 columns]

# HAndling missing data

In [ ]:
# df = df.dropna(subset=['Type2'])
df = df.fillna({"Type2":"None"}) #making the type2 column missing value into NONE instead of Nan is replace it with None
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire    None     0.6     8.5          0
4      5  Charmeleon     Fire    None     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon    None     1.8     3.3          0
147  148   Dragonair   Dragon    None     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic    None     2.0   122.0          1

[150 rows x 7 columns]

# Fix inconsistent values

In [ ]:
df['Type1'] = df['Type1'].replace({'Grass':'GRASS','Fire':'FIRE','Water':'WATER'}) # replace the values in the type1 column into upper case
df.head(50)

    No        Name     Type1   Type2  Height  Weight  Legendary
0    1   Bulbasaur     GRASS  Poison     0.7     6.9          0
1    2     Ivysaur     GRASS  Poison     1.0    13.0          0
2    3    Venusaur     GRASS  Poison     2.0   100.0          0
3    4  Charmander      FIRE    None     0.6     8.5          0
4    5  Charmeleon      FIRE    None     1.1    19.0          0
5    6   Charizard      FIRE  Flying     1.7    90.5          0
6    7    Squirtle     WATER    None     0.5     9.0          0
7    8   Wartortle     WATER    None     1.0    22.5          0
8    9   Blastoise     WATER    None     1.6    85.5          0
9   10    Caterpie       Bug    None     0.3     2.9          0
10  11     Metapod       Bug    None     0.7     9.9          0
11  12  Butterfree       Bug  Flying     1.1    32.0          0
12  13      Weedle       Bug  Poison     0.3     3.2          0
13  14      Kakuna       Bug  Poison     0.6    10.0          0
14  15    Beedrill       Bug  Poison     1.0    29.5          0
15  16      Pidgey    Normal  Flying     0.3     1.8          0
16  17   Pidgeotto    Normal  Flying     1.1    30.0          0
17  18     Pidgeot    Normal  Flying     1.5    39.5          0
18  19     Rattata    Normal    None     0.3     3.5          0
19  20    Raticate    Normal    None     0.7    18.5          0
20  21     Spearow    Normal  Flying     0.3     2.0          0
21  22      Fearow    Normal  Flying     1.2    38.0          0
22  23       Ekans    Poison    None     2.0     6.9          0
23  24       Arbok    Poison    None     3.5    65.0          0
24  25     Pikachu  Electric    None     0.4     6.0          0
25  26      Raichu  Electric    None     0.8    30.0          0
26  27   Sandshrew    Ground    None     0.6    12.0          0
27  28   Sandslash    Ground    None     1.0    29.5          0
28  29    Nidoran♀    Poison    None     0.4     7.0          0
29  30    Nidorina    Poison    None     0.8    20.0          0
30  31   Nidoqueen    Poison  Ground     1.3    60.0          0
31  32    Nidoran♂    Poison    None     0.5     9.0          0
32  33    Nidorino    Poison    None     0.9    19.5          0
33  34    Nidoking    Poison  Ground     1.4    62.0          0
34  35    Clefairy     Fairy    None     0.6     7.5          0
35  36    Clefable     Fairy    None     1.3    40.0          0
36  37      Vulpix      FIRE    None     0.6     9.9          0
37  38   Ninetales      FIRE    None     1.1    19.9          0
38  39  Jigglypuff    Normal   Fairy     0.5     5.5          0
39  40  Wigglytuff    Normal   Fairy     1.0    12.0          0
40  41       Zubat    Poison  Flying     0.8     7.5          0
41  42      Golbat    Poison  Flying     1.6    55.0          0
42  43      Oddish     GRASS  Poison     0.5     5.4          0
43  44       Gloom     GRASS  Poison     0.8     8.6          0
44  45   Vileplume     GRASS  Poison     1.2    18.6          0
45  46       Paras       Bug   Grass     0.3     5.4          0
46  47    Parasect       Bug   Grass     1.0    29.5          0
47  48     Venonat       Bug  Poison     1.0    30.0          0
48  49    Venomoth       Bug  Poison     1.5    12.5          0
49  50     Diglett    Ground    None     0.2     0.8          0

# Standardizre text

In [ ]:
df['Name'] = df['Name'].str.lower() #making all the name in column name into smaller case
df

# Fix data types

In [29]:
df['Legendary'] = df['Legendary'].astype(bool) # previously the data in the legendary column is 0 or 1 now we changed the data type to boolean so it now in 0 For False 1 For True
df.tail(60)

      No        Name     Type1    Type2  Height  Weight  Legendary
90    91    Cloyster     WATER      Ice     1.5   132.5      False
91    92      Gastly     Ghost   Poison     1.3     0.1      False
92    93     Haunter     Ghost   Poison     1.6     0.1      False
93    94      Gengar     Ghost   Poison     1.5    40.5      False
94    95        Onix      Rock   Ground     8.8   210.0      False
95    96     Drowzee   Psychic     None     1.0    32.4      False
96    97       Hypno   Psychic     None     1.6    75.6      False
97    98      Krabby     WATER     None     0.4     6.5      False
98    99     Kingler     WATER     None     1.3    60.0      False
99   100     Voltorb  Electric     None     0.5    10.4      False
100  101   Electrode  Electric     None     1.2    66.6      False
101  102   Exeggcute     GRASS  Psychic     0.4     2.5      False
102  103   Exeggutor     GRASS  Psychic     2.0   120.0      False
103  104      Cubone    Ground     None     0.4     6.5      False
104  105     Marowak    Ground     None     1.0    45.0      False
105  106   Hitmonlee  Fighting     None     1.5    49.8      False
106  107  Hitmonchan  Fighting     None     1.4    50.2      False
107  108   Lickitung    Normal     None     1.2    65.5      False
108  109     Koffing    Poison     None     0.6     1.0      False
109  110     Weezing    Poison     None     1.2     9.5      False
110  111     Rhyhorn    Ground     Rock     1.0   115.0      False
111  112      Rhydon    Ground     Rock     1.9   120.0      False
112  113     Chansey    Normal     None     1.1    34.6      False
113  114     Tangela     GRASS     None     1.0    35.0      False
114  115  Kangaskhan    Normal     None     2.2    80.0      False
115  116      Horsea     WATER     None     0.4     8.0      False
116  117      Seadra     WATER     None     1.2    25.0      False
117  118     Goldeen     WATER     None     0.6    15.0      False
118  119     Seaking     WATER     None     1.3    39.0      False
119  120      Staryu     WATER     None     0.8    34.5      False
120  121     Starmie     WATER  Psychic     1.1    80.0      False
121  122    Mr. Mime   Psychic    Fairy     1.3    54.5      False
122  123     Scyther       Bug   Flying     1.5    56.0      False
123  124        Jynx       Ice  Psychic     1.4    40.6      False
124  125  Electabuzz  Electric     None     1.1    30.0      False
125  126      Magmar      FIRE     None     1.3    44.5      False
126  127      Pinsir       Bug     None     1.5    55.0      False
127  128      Tauros    Normal     None     1.4    88.4      False
128  129    Magikarp     WATER     None     0.9    10.0      False
129  130    Gyarados     WATER   Flying     6.5   235.0      False
130  131      Lapras     WATER      Ice     2.5   220.0      False
131  132       Ditto    Normal     None     0.3     4.0      False
132  133       Eevee    Normal     None     0.3     6.5      False
133  134    Vaporeon     WATER     None     1.0    29.0      False
134  135     Jolteon  Electric     None     0.8    24.5      False
135  136     Flareon      FIRE     None     0.9    25.0      False
136  137     Porygon    Normal     None     0.8    36.5      False
137  138     Omanyte      Rock    Water     0.4     7.5      False
138  139     Omastar      Rock    Water     1.0    35.0      False
139  140      Kabuto      Rock    Water     0.5    11.5      False
140  141    Kabutops      Rock    Water     1.3    40.5      False
141  142  Aerodactyl      Rock   Flying     1.8    59.0      False
142  143     Snorlax    Normal     None     2.1   460.0      False
143  144    Articuno       Ice   Flying     1.7    55.4       True
144  145      Zapdos  Electric   Flying     1.6    52.6       True
145  146     Moltres      FIRE   Flying     2.0    60.0       True
146  147     Dratini    Dragon     None     1.8     3.3      False
147  148   Dragonair    Dragon     None     4.0    16.5      False
148  149   Dragonite    Dragon   Flying     2.2   210.0      False
149  150      Mewtwo   Psychic     None     2.0   122.0       True

# Remove duplicate values

In [30]:
df = df.drop_duplicates()
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    GRASS  Poison     0.7     6.9      False
1      2     Ivysaur    GRASS  Poison     1.0    13.0      False
2      3    Venusaur    GRASS  Poison     2.0   100.0      False
3      4  Charmander     FIRE    None     0.6     8.5      False
4      5  Charmeleon     FIRE    None     1.1    19.0      False
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     FIRE  Flying     2.0    60.0       True
146  147     Dratini   Dragon    None     1.8     3.3      False
147  148   Dragonair   Dragon    None     4.0    16.5      False
148  149   Dragonite   Dragon  Flying     2.2   210.0      False
149  150      Mewtwo  Psychic    None     2.0   122.0       True

[150 rows x 7 columns]