#### import the libraries

In [32]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [33]:
df =pd.read_csv('Data.csv')
df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     str
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     str
dtypes: float64(2), str(2)
memory usage: 452.0 bytes

In [35]:
df.describe()

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [36]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [37]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

In [38]:

df.head()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0  61000.0       Yes

In [41]:
from sklearn.preprocessing import LabelEncoder

lr = LabelEncoder()

df['Purchased'] = lr.fit_transform(df['Purchased'])
country_map = {'France':0,'Spain':1,'Germany':2}
df['Country'] = df['Country'].map(country_map)

In [42]:
df

   Country   Age   Salary  Purchased
0        0  44.0  72000.0          0
1        1  27.0  48000.0          1
2        2  30.0  54000.0          0
3        1  38.0  61000.0          0
4        2  40.0  61000.0          1
5        0  35.0  58000.0          1
6        1  38.0  52000.0          0
7        0  48.0  79000.0          1
8        2  50.0  83000.0          0
9        0  37.0  67000.0          1